# Generated by Django 4.0.6 on 2022-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время сокращения ссылки'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='full_link',
            field=models.URLField(verbose_name='Полная ссылка в формате http://...'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_link',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
