# Generated by Django 4.0.6 on 2022-07-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_shortlink_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_link',
            field=models.CharField(blank=True, max_length=28, unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
