# Generated by Django 4.0.6 on 2022-07-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_shortlink_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='full_link',
            field=models.URLField(unique=True, verbose_name='Полная ссылка в формате http://...'),
        ),
    ]
